import {
  ORDERS_TABLE_NAME,
  PRODUCTS_TABLE_NAME,
  PRODUCT_LIKES_TABLE_NAME,
  PRODUCT_SIZES_TABLE_NAME,
  PRODUCT_SKU_TABLE_NAME,
  USERS_TABLE_NAME,
} from "@repo/db/constants";

export const getDbInfoTables = [
  ORDERS_TABLE_NAME,
  PRODUCT_LIKES_TABLE_NAME,
  USERS_TABLE_NAME,
  PRODUCT_SKU_TABLE_NAME,
  PRODUCTS_TABLE_NAME,
  PRODUCT_SIZES_TABLE_NAME,
] as const;
